# NumPy (Numerical Python)

NumPy treballa amb objectes d'arrays homogenis multidimensionals i proporciona una col·lecció de funcions per processar aquests arrays. NumPy és conegut pels càlculs numèrics ràpids. Numpy proporciona una sintaxi de nivell alt i té un ecosistema molt vibrant que s'interrelaciona amb diferents àrees d'aplicació. Els arrays n-dimensionals s'anomenen ndarray. ndarray forma els blocs de construcció primitives de nombroses llibreries de Python.


# Importing numpy

NumPy està disponible per defecte als quaderns de Colab. Per tant, la llibreria es pot invocar directament utilitzant l'expressió import.


In [1]:
import numpy as np
print("Loaded", np.__version__, "version of numpy!!!")

Loaded 1.26.3 version of numpy!!!


# Creant NumPy arrays

El ndarray bàsic es crea utilitzant la funció **array**, la qual accepta qualsevol seqüència com a paràmetre d'entrada. Els arrays de NumPy es poden crear fàcilment a partir de llistes.



In [2]:
# creating a 1 dimensional array
var1 = np.array([1, 2, 3, 4, 5])

# creating a 2 dimensional array
var2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 0]])

print("var1 =", var1)
print("var2 =", var2)

var1 = [1 2 3 4 5]
var2 = [[1 2 3 4 5]
 [6 7 8 9 0]]


In [4]:
# També és possible especificar el tipus de l'element durant la creació de l'array
var3 = np.array([1, 2, 3], dtype=np.float32)
print("var3 =", var3)

# Es pot fer ús d'arrays de NumPy per crear un altre array amb un dtype diferent.
var4 = np.array(var3, dtype=np.int32)
print("var4 =", var4)

var5 = np.array(var4, dtype=np.complex_)
print("var5 =", var5)

var3 = [1. 2. 3.]
var4 = [1 2 3]
var5 = [1.+0.j 2.+0.j 3.+0.j]


# Propietats de l'Array
Els atributs més importants dels que disposa són:

*   shape: Dimensions de l'array
*   size: Nombre  d'elements de l'array
*   ndim: Nombre d'eixos
*   dtype: Tipus d'elements de l'array



In [5]:
print(var1.dtype, '\t \t', var1.shape, '\t \t', var1.size, '\t', var1.ndim)
print(var2.dtype, '\t \t', var2.shape, '\t', var2.size, '\t', var2.ndim)
print(var3.dtype, '\t', var3.shape, '\t \t', var3.size, '\t', var3.ndim)
print(var4.dtype, '\t \t', var4.shape, '\t \t', var4.size, '\t', var4.ndim)
print(var5.dtype, '\t', var5.shape, '\t \t', var5.size, '\t', var5.ndim)

int32 	 	 (5,) 	 	 5 	 1
int32 	 	 (2, 5) 	 10 	 2
float32 	 (3,) 	 	 3 	 1
int32 	 	 (3,) 	 	 3 	 1
complex128 	 (3,) 	 	 3 	 1


# Altres mètodes de creació d'arrays

No sempre és necessari tenir els elements definits durant la creació dels arrays. Hi ha diverses funcions de NumPy que permeten crear arrays per actuar com a placeholders abans de les computacions reals.


**Exercise #01:**

*   Crea diferents objectes d'array utilitzant les següents funcions:

1. zeros
2. ones
3. empty
4. zeros_like
5. ones_like
6. empty_like


In [27]:
array = np.zeros((2,2,3))
array1 = np.ones((2,2,4))
array_empty = np.empty((2,2,3))
array_zeros = np.zeros_like(array1)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


**Exercise #02:**

*  Quina és la diferència entre els mètodes **empty** i  **zeros**?
*  Quin és l'ús de les funcions **arange** i **linspace**?





**Solution**

Escriu aqui la teva solució

# Shape Manipulations

In [43]:
# Creant numpy array fent servir arange function
var6 = np.arange(12, dtype=np.int32)
print(var6)

# Reshaping el array a 2x6
var6 = var6.reshape(2,6)
print(var6)

# Reshaping del array array a 3 dimensions
var6 = var6.reshape(3,2,2)
print(var6)

var7 = np.resize(var6, (6,6,6))
print(var7.shape)
print(var6.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(3, 2, 2)


**Exercise #03:**

*  Quina és la diferència entre reshape i resize?



**Solution**


...

# Indexing, Slicing and Iterating

L'indexació és similar a les llistes de Python. Utilitzem l'operador [ ] per proporcionar índexos.


In [46]:
var7 = np.array([1, 2, 3, 4, 5])

# indexant el segon element
# Recordeu que els arrays sempre comencen en 0
print(var7[1])

# Printejant els dos primers elements
print(var7[1:3])

2
[2 3]


In [48]:
# És possible seleccionar/printejar els elements bassats en una condició
print(var7[var7 % 2 == 0])  # Printeja tots els elements d'un array que son parells

[2 4]


In [ ]:
var8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(var8)

# indexant el element de la 2 columna el 2 element
print(var8[1,1])

# Es possible seleccionar totes les files però només una única columna
print(var8[1])
print(var8[:,1])

# O un mix
print(var8[0:2, 0:2])

**Exercise #04:**

*   What is the use of non-zero function? Provide an example of how non-zero function can be used.



**Solution**

...

Iterar un array es pot fer de la mateixa forma que es recorre una llista en python

In [53]:
var9 = np.array([[1, 2, 3], [4, 5, 6]])

for i in var9: 
    print(i) 

for i in var9: 
    for j in i: 
        print(j) 

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [54]:
var10 = np.array([[1, 2, 3], [4, 5, 6]])
var10=np.resize(var10,(2,2,2))
for i in np.nditer(var10):
    print(i)

1
2
3
4
5
6
1
2


**Exercise #05:**

*   Com poder fer un enumerate amb numpy?



**Solution**



In [ ]:
# La teva solució aqui

Cal tenir en compte que, les slices comparteixen memòria amb la matriu original.

A l'exemple següent, var12 es crea tallant var11. Observeu el canvi a var11 després de modificar var12.

In [55]:
var11 = np.array([1, 2, 3])

var12 = var11[0:1]
print(var12)
print('before changing:', var11)
var12[0] = 4
print('after changing:', var11)

[1]
before changing: [1 2 3]
after changing: [4 2 3]


# Array Copy

Quan creeu una matriu nova utilitzant l'operador '=', no es crea cap còpia nova de la matriu, és a dir, només es crea un nom però fa referència al mateix objecte.

In [ ]:
var13 = np.array([1, 2, 3, 4, 5])

var14 = var13
print('Before modifying', var13)

var14[0] += 1
print('After modifying', var13)

Quan s'utilitza una funció de vista per crear una còpia de la matriu, o quan la matriu es talla, la matriu retornada només és una còpia superficial de la matriu original, és a dir, es crea un objecte matriu però l'objecte apunta a les mateixes dades.

In [ ]:
var15 = np.array([1, 2, 3, 4, 5])

var16 = var15.view()
print('Before modifying (using view)', var15)

var16[0] += 1
print('After modifying (using view)', var15)

var17 = var15[0:3]
print('Before modifying (using slice)', var15)

var17[2] += 1
print('After modifying (using slice)', var15)

Per crear una còpia profunda de la matriu, cal utilitzar el mètode de còpia

In [56]:
var18 = np.array([1, 2, 3, 4, 5])

var19 = var18.copy()
print('Before modifying (using copy)', var18)

var19[0] += 1
print('After modifying (using copy)', var18)

Before modifying (using copy) [1 2 3 4 5]
After modifying (using copy) [1 2 3 4 5]


# Afegint un nou eix

També és possible augmentar les dimensions d'una matriu numpy. **np.newaxis** i **expand_dims** es poden utilitzar per augmentar les dimensions de la matriu. Això seria molt útil per construir xarxes neuronals convolucionals on hauríeu de tenir longituds de canal uniformes *(s'utilitzarà en els exercicis posteriors)*.

In [ ]:
var20 = np.array([1, 2, 3, 4, 5])
print(var20.shape)

a = var20[np.newaxis, :]  # adding new axis to the first axis
print(a.shape)

b = a[np.newaxis, :]  # adding new axis to the first axis
print(b.shape)

c = np.expand_dims(var20, axis=1)  # adding new axis to the second component
print(c.shape)

d = np.expand_dims(var20, axis=0)  # adding new axis to the first component
print(d.shape)

# Broadcasting Rules

La difusió tracta de com numpy tracta les matrius amb diferents mides durant les operacions aritmètiques. En general, les matrius més petites es transmeten a les formes de matriu més grans de manera que ambdues matrius siguin compatibles.


In [ ]:
var20 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

print(var20)

print(var20 * 2)  # multiplying each element with 2

print(var20 + [1, 0, 1])  # adding each row with [1, 0, 1]]

**Exercise #06:**

La normalització de valors és una àrea important en qualsevol problema de processament d'imatges i aprenentatge automàtic. En aquest exercici, intentarem aplicar la normalització en diferents eixos per entendre el paper del broadcasting.

In [ ]:
var21 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

# calcula la mitjana de les files
# calcula la mitjana de columna
# feu la resta de mitjana per fila i la resta de mitjana per columna
# com normalitzem tota la matriu utilitzant la mitjana global?

